### PR TITLE
ubuntu: test intel compiler

### PR DESCRIPTION
**Pull request by junghans**
https://github.com/ECP-copa/Cabana/pull/740#issuecomment-2010419463

### CODE REVIEW

**Comment by junghans** [comment]
@streeve I am a bit confused why it can find `icpx` here.....

**Comment by streeve** [comment]
> @streeve I am a bit confused why it can find `icpx` here.....

I'm very confused - CI started working again after you opened this..

**Comment by streeve** [comment]
I think this worked because the Kokkos/ci-container was rebuilt just before

**Comment by junghans** [comment]
@streeve should we merge this?

**Pull request closed without merging**
